#
###################################
# Site wide configuration
####################################
#
title: a cosmic ray
email: rayssa17@astro.ufrj.br
description: Data visualization, Python, Python & Python.
url: http://rayssags.github.io
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Sao_Paulo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: a cosmic ray
  avatar: leonids-logob.png
  job: "Geek bookworm observing galaxies in MIR"
  bio: "Data visualization, Python, Python & Python."
  email:
  disqus-shortname:
  twitter: ray_gmrs
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rayssags
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: acosmicray
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
